I think this is the end of whitespace hell

diff --git a/justboot.in b/justboot.in
--- a/justboot.in
+++ b/justboot.in
@@ -857,29 +857,29 @@ else
 fi
 
 for i in "${livecd_excludes[@]}"; do
-    if (shopt -s nullglob dotglob; f=(${excludes_dir}/${i//\//:}/!(.keep));\
-    (( ${#f[@]} ))); then
-        einfo "Copying ${blue}${i}${nocolor} to ${red}${target}/\
+	if (shopt -s nullglob dotglob; f=(${excludes_dir}/${i//\//:}/!(.keep));\
+(( ${#f[@]} ))); then
+		einfo "Copying ${blue}${i}${nocolor} to ${red}${target}/\
 ${i}.${nocolor} please wait..."
-        do_exec cp -a ${excludes_dir}/${i//\//:}/* ${target}/${i} \
+		do_exec cp -a ${excludes_dir}/${i//\//:}/* ${target}/${i} \
 &>/dev/null  
-    fi
+	fi
 done
 
 if ${ramfs}; then
-    for x in "${ramfs_dir[@]}"; do
-        for y in "${livecd_excludes[@]}"; do
-            [[ ${x} = ${y} ]] && continue 2
-        done
+	for x in "${ramfs_dir[@]}"; do
+		for y in "${livecd_excludes[@]}"; do
+			[[ ${x} = ${y} ]] && continue 2
+		done
 
 	if (shopt -s nullglob dotglob; f=(${excludes_dir}/${x//\//:}/!(.keep));\
-        (( ${#f[@]} ))); then
-            einfo "Copying ${blue}${x}${nocolor} to ${red}${target}/\
+(( ${#f[@]} ))); then
+		einfo "Copying ${blue}${x}${nocolor} to ${red}${target}/\
 ${x}.${nocolor} please wait..."
-            do_exec cp -a ${excludes_dir}/${x//\//:}/* ${target}/\
+		do_exec cp -a ${excludes_dir}/${x//\//:}/* ${target}/\
 ${x} &>/dev/null
-        fi
-    done
+	fi
+	done
 fi
 
 cat >> ${cleanup_script} << CLEANUP
@@ -891,8 +891,8 @@ echo "Entering livecd environment"
 env-update 1>/dev/null && source /etc/profile
 
 for i in ${remove_packages[@]}; do
-    echo "Removing \${i} from livecd"
-    ${pms} -C \${i} &>/dev/null
+	echo "Removing \${i} from livecd"
+	${pms} -C \${i} &>/dev/null
 done
 
 echo -e "${red}${#remove_packages[@]}${nocolor} Packages removed"
@@ -900,12 +900,12 @@ exit
 CLEANUP
 
 do_exec chmod +x ${cleanup_script} && \
-    do_exec mv ${cleanup_script} ${target}/tmp
+	do_exec mv ${cleanup_script} ${target}/tmp
 
 if [[ ${arch} =~ ^i[4-6]86$ ]]; then
-    do_exec linux32 chroot ${target} ${cleanup_script}
+	do_exec linux32 chroot ${target} ${cleanup_script}
 else
-    do_exec linux64 chroot ${target} ${cleanup_script}
+	do_exec linux64 chroot ${target} ${cleanup_script}
 fi
 
 [[ $? =~ ^(1|13)$ ]] && do_exec release_env now
@@ -916,8 +916,8 @@ do_exec rm -rf ${remove_files[@]} ${livecd_excludes[@]}
 if ${ramfs}; then do_exec umount ${ramfs_dir[@]}; fi
 
 for i in boot var/run/dbus var/lock/subsys var/cache/edb/deb \
-    var/cache/hald var/log root var/log; do
-    do_exec exec_chkdir ${i}
+	var/cache/hald var/log root var/log; do
+	do_exec exec_chkdir ${i}
 done
 
 >etc/mtab
@@ -985,46 +985,46 @@ trap 'echo "User interrupted, Exiting"; exit $USER_INTERRUPT' TERM INT
 env-update 1>/dev/null && source /etc/profile
 
 einfo() {
-    echo -e ".: "\${@}" :."
+	echo -e ".: "\${@}" :."
 }
 ewarn() {
-    echo -e "\a\${red}.: "\${@}" :.\${nocolor}"
+	echo -e "\a\${red}.: "\${@}" :.\${nocolor}"
 }
 error() { 
-    echo -e "\a\${red}.: "\${@}" :.\${nocolor}"
-    exit 1
+	echo -e "\a\${red}.: "\${@}" :.\${nocolor}"
+	exit 1
 }
 do_exec() {
 if ${debug}; then
-    echo -e "\a\${red}debug:\${nocolor}\${blue} (\${@})"\${nocolor}
-    "\${@}"
+	echo -e "\a\${red}debug:\${nocolor}\${blue} (\${@})"\${nocolor}
+	"\${@}"
 elif ${verbose}; then
-    "\${@}"
+	"\${@}"
 else
-    "\${@}" 2>/dev/null
+	"\${@}" 2>/dev/null
 fi
 }
 
 check_deps() {
 # Check for pkgcore if --package-manager=pkgcore is used
 if [[ "${pms/ -q/}" = pmerge ]]; then
-    if ! hash pmerge &>/dev/null; then
-        einfo "Compiling \${blue}sys-apps/pkgcore\${nocolor}"
-        do_exec emerge pkgcore 1>/dev/null
-    fi
+	if ! hash pmerge &>/dev/null; then
+		einfo "Compiling \${blue}sys-apps/pkgcore\${nocolor}"
+		do_exec emerge pkgcore 1>/dev/null
+	fi
 fi
 
 # Check for initramfs compression tools
 local -a compression_tools=( 'lzma:app-arch/xz-utils'
-    'lzop:app-arch/lzop' ) 
+	'lzop:app-arch/lzop' ) 
 
 for i in \${compression_tools[@]}; do
-    if [ ${init_compression} = \${i/:*/} ]; then
-        if ! hash \${i/:*/} &>/dev/null; then
-            do_exec ${pms} \${i/*:/} 1>/dev/null
-            break
-        fi
-    fi
+	if [ ${init_compression} = \${i/:*/} ]; then
+		if ! hash \${i/:*/} &>/dev/null; then
+			do_exec ${pms} \${i/*:/} 1>/dev/null
+			break
+		fi
+	fi
 done
 }
 
@@ -1033,7 +1033,7 @@ do_exec cp -a ${data_dir}/etc/{fstab,portage} /etc
 do_exec cp -a ${data_dir}/etc/conf.d/{hostname,net,clock} /etc/conf.d
 
 if [[ ! \$(grep JustBOOT /etc/make.conf 2>/dev/null) ]]; then
-    >/etc/make.conf
+	>/etc/make.conf
 # Generate our make.conf if this is a new livecd build.
 cat >> /etc/make.conf << MAKECONF
 # /etc/make.conf generated by the JustBOOT(tm) livecd generator
@@ -1060,66 +1060,66 @@ fi
 
 # Prepare the livecd required and user packages.
 prepare_packages() {
-local -a global_packages=( 'net-setup:app-misc/livecd-tools' 
-	'lshw:sys-apps/lshw' 'mkfs.reiser4:sys-fs/reiser4progs' 
-	'mkfs.jfs:sys-fs/jfsutils' 'mkfs.xfs:sys-fs/xfsprogs' 
+local -a global_packages=( 'net-setup:app-misc/livecd-tools'
+	'lshw:sys-apps/lshw' 'mkfs.reiser4:sys-fs/reiser4progs'
+	'mkfs.jfs:sys-fs/jfsutils' 'mkfs.xfs:sys-fs/xfsprogs'
 	'mkfs.reiserfs:sys-fs/reiserfsprogs' 'mdadm:sys-fs/mdadm'
-	'screen:app-misc/screen' 'rsync:net-misc/rsync' 
-	'dhcpcd:net-misc/dhcpcd' 'ntpd:net-misc/openntpd' 
+	'screen:app-misc/screen' 'rsync:net-misc/rsync'
+	'dhcpcd:net-misc/dhcpcd' 'ntpd:net-misc/openntpd'
 	'sudo:app-admin/sudo' )
 
 einfo "Preparing livecd and user packages. please wait..."
 for i in \${global_packages[@]}; do
-    if ! hash \${i/:*/} &>/dev/null; then 
-        einfo "Compiling \${blue}\${i/*:/}\${nocolor}"
-        do_exec ${pms} \${i/*:/} 1>/dev/null
-    fi
+	if ! hash \${i/:*/} &>/dev/null; then
+		einfo "Compiling \${blue}\${i/*:/}\${nocolor}"
+		do_exec ${pms} \${i/*:/} 1>/dev/null
+	fi
 done
 
 for i in ${extra_packages[@]}; do
-    if ! hash \${i/:*/} &>/dev/null; then
-        einfo "Compiling \${blue}\${i}\${nocolor}"
-        do_exec ${pms} \${i/*:/} 1>/dev/null
-    fi
+	if ! hash \${i/:*/} &>/dev/null; then
+		einfo "Compiling \${blue}\${i}\${nocolor}"
+		do_exec ${pms} \${i/*:/} 1>/dev/null
+	fi
 done
 
 if ! hash memtest86+ &>/dev/null; then
-    do_exec ${pms} memtest86+ 1>/dev/null
+	do_exec ${pms} memtest86+ 1>/dev/null
 fi
 
 # Setup sudoers
 [ -f /etc/sudoers ] && sed -i '/NOPASSWD: ALL/ s/^# //' /etc/sudoers
 }
 
-fetch_archive() { 
+fetch_archive() {
 while [ \$# -gt 0 ]; do
-    case "\$1" in
-        busybox)
-            einfo "Fetching Busybox sources"
-            do_exec wget -q \${busybox_src_uri}
+	case "\$1" in
+		busybox)
+			einfo "Fetching Busybox sources"
+			do_exec wget -q \${busybox_src_uri}
 
-            einfo "Extracting Busybox sources"
-            do_exec tar xjpf \${busybox_archive}
-        ;;
-        uclibc)
-            einfo "Fetching Gentoo UCLIBC stage3 tarball"
-            do_exec wget -q \${uclibc_src_uri}
+			einfo "Extracting Busybox sources"
+			do_exec tar xjpf \${busybox_archive}
+			;;
+		uclibc)
+			einfo "Fetching Gentoo UCLIBC stage3 tarball"
+			do_exec wget -q \${uclibc_src_uri}
 
-            einfo "Extracting Gentoo uclibc stage3 tarball"
-            do_exec tar xjpf stage*
-    esac
-    shift
+			einfo "Extracting Gentoo uclibc stage3 tarball"
+			do_exec tar xjpf stage*
+		esac
+		shift
 done
 }
 
 prepare_busybox() {
 if [ ! -d \${uclibc} ]; then
-    do_exec mkdir -p \${uclibc}
-    do_exec cd \${uclibc}
+	do_exec mkdir -p \${uclibc}
+	do_exec cd \${uclibc}
 
-    do_exec fetch_archive uclibc busybox
+	do_exec fetch_archive uclibc busybox
 elif  [[ ! -d \${uclibc}/\${busybox} ]]; then
-    do_exec cd \${uclibc} && do_exec fetch_archive busybox
+	do_exec cd \${uclibc} && do_exec fetch_archive busybox
 fi
 
 do_exec cp -a ${data_dir}/busybox/.config \${uclibc}/\${busybox}
@@ -1175,7 +1175,7 @@ if [[ ${procs[${cpu}]} =~ ^M([5-6]86|PENTIUM(4|M|II|III)|CORE2|ATOM|K[6-8])$ \
 back to K8!"
 		cpu=K8
 	fi
-    patch -sp0 <${kernel_sources}-${procs[${cpu}]}.patch
+		patch -sp0 <${kernel_sources}-${procs[${cpu}]}.patch
 fi
 }
 
@@ -1199,7 +1199,7 @@ fi
 do_kernel_compile() {
 if ! grep "sys-kernel/${kernel_sources} symlink" \
 /etc/portage/package.use 1>/dev/null; then
-    echo "sys-kernel/${kernel_sources} symlink">>/etc/portage/\
+	echo "sys-kernel/${kernel_sources} symlink">>/etc/portage/\
 package.use
 fi
 
@@ -1284,16 +1284,16 @@ fi
 kernel source directory"
 
 	if ${menuconfig}; then
-      do_exec make menuconfig
-      do_exec make ${MAKEOPTS} 1>/dev/null
-    else
-      do_exec make ${MAKEOPTS} 1>/dev/null
-    fi
+		do_exec make menuconfig
+		do_exec make ${MAKEOPTS} 1>/dev/null
+	else
+		do_exec make ${MAKEOPTS} 1>/dev/null
+	fi
 
-    do_exec make modules_install 1>/dev/null
-    einfo "\${red}\${arch}\${nocolor} kernel compiled, preparing \
-        initramfs image"
-    do_exec prepare_initramfs
+	do_exec make modules_install 1>/dev/null
+	einfo "\${red}\${arch}\${nocolor} kernel compiled, preparing \
+initramfs image"
+	do_exec prepare_initramfs
 fi
 
 do_exec cd /usr/src/linux || error "Failed to switch to \
@@ -1323,72 +1323,72 @@ einfo "Root passwd set to \${red}\"${root_passwd}\"\${nocolor}"
 }
 
 diff () {
-    printf '%s' \$(( \$(date -u -d"\$target" +%s) - \
-        \$(date -u -d"\$current" +%s)))
+	printf '%s' \$(( \$(date -u -d"\$target" +%s) - \
+\$(date -u -d"\$current" +%s)))
 }
 
 check_toolchain_days() {
 if [[ ${arch} = i586 && ! -f /etc/toolchain_age ]]; then
-    ewarn "i586 needs a toolchain build, setting --force-toolchain flag"
-    yes_tool=true
+	ewarn "i586 needs a toolchain build, setting --force-toolchain flag"
+	yes_tool=true
 fi
 
 if ${no_tool}; then
-    ewarn "Skipping toolchain build"
-    return 1
-    elif ${yes_tool}; then
-        ewarn "Forcing a toolchain build"
-        date -u -d '2 days' '+%F %T.%N %Z'>/etc/toolchain_age
-        return 0
-    else
+	ewarn "Skipping toolchain build"
+	return 1
+elif ${yes_tool}; then
+	ewarn "Forcing a toolchain build"
+	date -u -d '2 days' '+%F %T.%N %Z'>/etc/toolchain_age
+	return 0
+else
 
-    [ ! -f /etc/toolchain_age ] && date -u -d 'now' '+%F %T.%N %Z'>\
-        /etc/toolchain_age
+	[ ! -f /etc/toolchain_age ] && date -u -d 'now' '+%F %T.%N %Z'>\
+/etc/toolchain_age
 
-    local current=\$(date -u -d 'now' '+%F %T.%N %Z')
-    local target=\$(</etc/toolchain_age)
-    local mphr=60 hpd=24 limit=60
+	local current=\$(date -u -d 'now' '+%F %T.%N %Z')
+	local target=\$(</etc/toolchain_age)
+	local mphr=60 hpd=24 limit=60
 
-    # current = now, target = Last time the toolchain was rebuild.  %F =
-    # full date, %T = %H:%M:%S, %N = nanoseconds, %Z = time zone.  mphr
-    # = Minutes per hour, hpd = Hours per day, limit = Days before a
-    # toolchain rebuild.
+	# current = now, target = Last time the toolchain was rebuild.  %F =
+	# full date, %T = %H:%M:%S, %N = nanoseconds, %Z = time zone.  mphr
+	# = Minutes per hour, hpd = Hours per day, limit = Days before a
+	# toolchain rebuild.
 
-    days=\$(( \$(diff) / \$mphr / \$mphr / \$hpd ))
-    current=\$(date -d"\$current +\$days days" '+%F %T.%N %Z')
-    toolchain_days=\$(printf '%s' "\$days")
-    days_left=\$((limit-toolchain_days))
+	days=\$(( \$(diff) / \$mphr / \$mphr / \$hpd ))
+	current=\$(date -d"\$current +\$days days" '+%F %T.%N %Z')
+	toolchain_days=\$(printf '%s' "\$days")
+	days_left=\$((limit-toolchain_days))
 
-    if ((toolchain_days>limit)); then
-        ewarn "Your toolchain is \${toolchain_days} days old passed the \
-            \${limit} days limit."
-        date -u -d '1 day' '+%F %T.%N %Z'>/etc/toolchain_age
-        einfo "Preparing to rebuild the toolchain."
-        return 0
-    elif ((toolchain_days==0)); then
-        # First day of toolchain build, increment by 1 day
-        date -u -d '2 days' '+%F %T.%N %Z'>/etc/toolchain_age
-        ewarn "You have \${days_left:-60} days left until your next \
-            schedule bootstrap."
-        einfo "Preparing to build the toolchain."
-        return 0
-    else
-        ewarn "You have \${days_left:-60} days left until your next \
-            schedule bootstrap"
-        return 1
-    fi
+	if ((toolchain_days>limit)); then
+		ewarn "Your toolchain is \${toolchain_days} days old passed the \
+\${limit} days limit."
+		date -u -d '1 day' '+%F %T.%N %Z'>/etc/toolchain_age
+		einfo "Preparing to rebuild the toolchain."
+		return 0
+	elif ((toolchain_days==0)); then
+		# First day of toolchain build, increment by 1 day
+		date -u -d '2 days' '+%F %T.%N %Z'>/etc/toolchain_age
+		ewarn "You have \${days_left:-60} days left until your next \
+schedule bootstrap."
+		einfo "Preparing to build the toolchain."
+		return 0
+	else
+		ewarn "You have \${days_left:-60} days left until your next \
+schedule bootstrap"
+		return 1
+	fi
 fi
 }
 
 bootstrap() {
 # Enable livecd and user locales (see @confdir@/locale.gen)
 if grep '#en_US ISO-8859-1' /etc/locale.gen &>/dev/null; then
-    einfo "Setting locales"
-    for i in ${locales[@]} "#en_US ISO-8859-1"; do
-        if ! egrep "^${i}" /etc/locale.gen &>/dev/null; then
-            sed -i "s/#\${i}/\${i}/" /etc/locale.gen
-        fi
-    done
+	einfo "Setting locales"
+	for i in ${locales[@]} "#en_US ISO-8859-1"; do
+		if ! egrep "^${i}" /etc/locale.gen &>/dev/null; then
+			sed -i "s/#\${i}/\${i}/" /etc/locale.gen
+		fi
+	done
 fi
 
 do_exec locale-gen 1>/dev/null
@@ -1401,46 +1401,46 @@ einfo "Updating portage tree"
 do_exec emerge --sync -q 1>/dev/null
 
 if ! ${no_tool}; then
-    einfo "Compiling the toolchain, this maybe take a while depending \
-        on hardware."
-    for i in portage gcc-config binutils linux-headers glibc gcc; do
-        einfo "Compiling \${blue}\${i}.\${nocolor}"
-        do_exec ${pms} -1 \${i} 1>/dev/null && einfo "\${blue}\${i}\
-            \${nocolor} compiled."
-    done
-    do_exec gcc-config 1 1>/dev/null && do_exec env-update 1>/dev/null \
-        && do_exec source /etc/profile
+	einfo "Compiling the toolchain, this maybe take a while depending \
+on hardware."
+	for i in portage gcc-config binutils linux-headers glibc gcc; do
+		einfo "Compiling \${blue}\${i}.\${nocolor}"
+		do_exec ${pms} -1 \${i} 1>/dev/null && einfo "\${blue}\${i}\
+\${nocolor} compiled."
+	done
+	do_exec gcc-config 1 1>/dev/null && do_exec env-update 1>/dev/null \
+&& do_exec source /etc/profile
 
-    ! grep "\-\-hash\-style" /etc/make.conf &>/dev/null && sed -i \
-        's/-Wl,/-Wl,--hash-style=gnu,/' /etc/make.conf
+	! grep "\-\-hash\-style" /etc/make.conf &>/dev/null && sed -i \
+'s/-Wl,/-Wl,--hash-style=gnu,/' /etc/make.conf
 
-    for i in binutils linux-headers glibc gcc; do
-        einfo "Compiling \${blue}\${i}.\${nocolor}"
-        do_exec ${pms} -1 \${i} 1>/dev/null && einfo "\${blue}\${i}\
-            \${nocolor} compiled."
-    done
-    einfo "Toolchain build finished, compiling system packages"
+	for i in binutils linux-headers glibc gcc; do
+		einfo "Compiling \${blue}\${i}.\${nocolor}"
+		do_exec ${pms} -1 \${i} 1>/dev/null && einfo "\${blue}\${i}\
+\${nocolor} compiled."
+	done
+	einfo "Toolchain build finished, compiling system packages"
 
-    while read ebuild; do
-        einfo "Compiling \${blue}\"\${ebuild}\"\${nocolor}"
-        do_exec ${pms} -1 "\${ebuild}" 1>/dev/null || \
-            echo "\${ebuild}" >>failed
-        einfo "\${blue}\"\${ebuild}\"\${nocolor} compiled"
-        [[ \${ebuild} = dev-lang/python && "${pms}" = pmerge ]] && \
-            python-updater &>/dev/null
-    done < <(emerge -ep --columns --color=n system | grep ebuild | \
-        awk '{print\$4}' | egrep -v "(glibc|/portage|binutils|gcc|linux-h)")
+	while read ebuild; do
+		einfo "Compiling \${blue}\"\${ebuild}\"\${nocolor}"
+		do_exec ${pms} -1 "\${ebuild}" 1>/dev/null || \
+		echo "\${ebuild}" >>failed
+		einfo "\${blue}\"\${ebuild}\"\${nocolor} compiled"
+		[[ \${ebuild} = dev-lang/python && "${pms}" = pmerge ]] && \
+python-updater &>/dev/null
+	done < <(emerge -ep --columns --color=n system | grep ebuild | \
+awk '{print\$4}' | egrep -v "(glibc|/portage|binutils|gcc|linux-h)")
 
-    while read ebuild; do
-        einfo "Compiling \${blue}\"\${ebuild}\"\${nocolor}"
-        do_exec ${pms} -1 "\${ebuild}" 1>/dev/null
-        einfo "\${blue}\"\${ebuild}\"\${nocolor} compiled"
-    done <failed
-    do_exec rm failed
+	while read ebuild; do
+		einfo "Compiling \${blue}\"\${ebuild}\"\${nocolor}"
+		do_exec ${pms} -1 "\${ebuild}" 1>/dev/null
+		einfo "\${blue}\"\${ebuild}\"\${nocolor} compiled"
+	done <failed
+	do_exec rm failed
 
-    einfo "Toolchain build completed"
+	einfo "Toolchain build completed"
 else
-    einfo "Toolchain built skipped"
+	einfo "Toolchain built skipped"
 fi
 }
 
@@ -1468,7 +1468,7 @@ CHROOT
 # Lets go already!
 [[ ! -d ${livedir} ]] && exec_chkdir ${livedir}
 do_exec cd ${livedir} || error "Failed to switch to livecd build \
-    directory! Exiting."
+directory! Exiting."
 do_exec check_deps && do_exec prepare_stage
 
 # vim: set tabstop=4 softtabstop=4 shiftwidth=4 noexpandtab textwidth=80:
