more whitespace fixes

diff --git a/justboot.in b/justboot.in
--- a/justboot.in
+++ b/justboot.in
@@ -453,71 +453,71 @@ if ${uclibc_bind}; then
     do_exec umount ${arch_dir}/var/tmp/justboot/uclibc
 else
     do_exec mv ${arch_dir}/var/tmp/justboot/uclibc \
-        /var/tmp/justboot/
+/var/tmp/justboot/
 fi
 
 if ${ramfs}; then
-    for x in "${livecd_excludes[@]}"; do
-        for y in "${ramfs_dir[@]}"; do
-            if [[ ${x} = ${y} ]]; then
-                einfo "Removing ${red}${x}${nocolor} from memory. \
-                    please wait..."
-                do_exec rsync -caq --delete-before \
-                    ${arch}/${x}/* ${excludes_dir}/${x//\//:} &>/dev/null
-                do_exec umount ${arch}/${x} &>/dev/null
-                einfo "Copied ${blue}${x}${nocolor} changes to \
-                ${red}${excludes_dir}/${x//\//:}${nocolor}"
-            continue 2
-            fi
-        done
-        do_exec umount ${arch}/${x} &>/dev/null
-    done
+	for x in "${livecd_excludes[@]}"; do
+		for y in "${ramfs_dir[@]}"; do
+			if [[ ${x} = ${y} ]]; then
+				einfo "Removing ${red}${x}${nocolor} from memory. \
+please wait..."
+				do_exec rsync -caq --delete-before \
+${arch}/${x}/* ${excludes_dir}/${x//\//:} &>/dev/null
+				do_exec umount ${arch}/${x} &>/dev/null
+				einfo "Copied ${blue}${x}${nocolor} changes to \
+${red}${excludes_dir}/${x//\//:}${nocolor}"
+				continue 2
+			fi
+		done
+		do_exec umount ${arch}/${x} &>/dev/null
+	done
 
-    for x in "${ramfs_dir[@]}"; do
-        for y in "${livecd_excludes[@]}"; do
-            [[ ${x} = ${y} ]] && continue 2
-        done
+	for x in "${ramfs_dir[@]}"; do
+		for y in "${livecd_excludes[@]}"; do
+			[[ ${x} = ${y} ]] && continue 2
+		done
 
-    einfo "Removing ${red}${x}${nocolor} from memory. please wait..."
-    do_exec rsync -caq --delete-before ${arch}/${x}/* \
-        ${excludes_dir}/${x//\//:} &>/dev/null
-    do_exec umount ${arch}/${x} \
-        &>/dev/null
-    einfo "Copied ${blue}${x}${nocolor} changes to \
-        ${red}${excludes_dir}/${x//\//:}${nocolor}"
-    done
+		einfo "Removing ${red}${x}${nocolor} from memory. please wait..."
+		do_exec rsync -caq --delete-before ${arch}/${x}/* \
+${excludes_dir}/${x//\//:} &>/dev/null
+		do_exec umount ${arch}/${x} \
+&>/dev/null
+		einfo "Copied ${blue}${x}${nocolor} changes to \
+${red}${excludes_dir}/${x//\//:}${nocolor}"
+	done
 else
-    for x in "${livecd_excludes[@]}"; do
-        do_exec umount ${arch}/${x} &>/dev/null
-    done
+	for x in "${livecd_excludes[@]}"; do
+		do_exec umount ${arch}/${x} &>/dev/null
+	done
 fi
 
 [ ! $1 ] && do_exec clean_env
 }
 
 trap 'release_env now; exit 13' TERM INT
-#  Cleans up the livecd environment if script is interrupted by
-#  Control-C.
+# Cleans up the livecd environment if script is interrupted by
+# Control-C.
 
 # Check local system for required packages
 check_deps() {
 local -a deps=( 'mksquashfs:sys-fs/squashfs-tools'
-    'mkisofs:virtual/cdrtools' 'isohybrid:sys-boot/syslinux' )
+	'mkisofs:virtual/cdrtools' 'isohybrid:sys-boot/syslinux' )
 
 if [[ "${pms/ -q/}" = pmerge ]]; then
-    if ! hash pmerge &>/dev/null; then
-        einfo "Compiling ${blue}sys-apps/pkgcore${nocolor}"
-        do_exec emerge pkgcore 1>/dev/null
-        einfo "${blue}sys-apps/pkgcore${nocolor} compiled"
-    fi
+	if ! hash pmerge &>/dev/null; then
+		einfo "Compiling ${blue}sys-apps/pkgcore${nocolor}"
+		do_exec emerge pkgcore 1>/dev/null
+		einfo "${blue}sys-apps/pkgcore${nocolor} compiled"
+	fi
 fi
 
 for i in ${deps[@]}; do
-    if ! hash ${i/:*/} &>/dev/null; then
-        einfo "Compiling ${blue}${i/*:/}${nocolor}"
-        do_exec ${pms} ${i/*:/} 1>/dev/null
-        einfo "${blue}${i/*:/}${nocolor} compiled"
-    fi
+	if ! hash ${i/:*/} &>/dev/null; then
+		einfo "Compiling ${blue}${i/*:/}${nocolor}"
+		do_exec ${pms} ${i/*:/} 1>/dev/null
+		einfo "${blue}${i/*:/}${nocolor} compiled"
+	fi
 done
 }
 
@@ -526,120 +526,120 @@ done
 # with --purge argument.
 prepare_stage() {
 if [[ ! -d ${arch_dir} || ${livedir} = /var/tmp/justboot ]]; then
-    if [ -h /var/tmp/justboot/${arch} ]; then
-        local real_arch_dir=$(readlink /var/tmp/justboot/${arch})
-        local real_excludes_dir=$(readlink \
-            /var/tmp/justboot/excludes/${arch})
+	if [ -h /var/tmp/justboot/${arch} ]; then
+		local real_arch_dir=$(readlink /var/tmp/justboot/${arch})
+		local real_excludes_dir=$(readlink \
+/var/tmp/justboot/excludes/${arch})
 
-        einfo "Moving build directory from ${red}${real_arch_dir}\
-            ${nocolor} to ${red}${livedir}/${arch}${nocolor}. \
-            please wait..."
+		einfo "Moving build directory from ${red}${real_arch_dir}\
+${nocolor} to ${red}${livedir}/${arch}${nocolor}. \
+please wait..."
 
-        for i in /var/tmp/justboot/${arch} \
-            /var/tmp/justboot/excludes/${arch}; do
-            do_exec unlink ${i}
-        done
+		for i in /var/tmp/justboot/${arch} \
+/var/tmp/justboot/excludes/${arch}; do
+			do_exec unlink ${i}
+		done
 
-        exec_chkdir ${livedir}/excludes
-        do_exec mv ${real_arch_dir} ${arch_dir}
-        do_exec mv ${real_excludes_dir} ${excludes_dir}
+		exec_chkdir ${livedir}/excludes
+		do_exec mv ${real_arch_dir} ${arch_dir}
+		do_exec mv ${real_excludes_dir} ${excludes_dir}
 
-        if [[ ${livedir} != /var/tmp/justboot ]]; then
-            do_exec ln -sf ${arch_dir} /var/tmp/justboot/${arch}
-            do_exec ln -sf ${livedir}/excludes/${arch} \
-                /var/tmp/justboot/excludes/${arch}
-            do_exec ln -sf @datdir@ ${data_dir}
-        fi
+		if [[ ${livedir} != /var/tmp/justboot ]]; then
+			do_exec ln -sf ${arch_dir} /var/tmp/justboot/${arch}
+			do_exec ln -sf ${livedir}/excludes/${arch} \
+/var/tmp/justboot/excludes/${arch}
+			do_exec ln -sf @datdir@ ${data_dir}
+		fi
 
-        for i in i{4,5,6}86 x86_64; do
-            [[ ${i} = ${arch} ]] && continue 2
-            [[ -d ${real_arch_dir/${arch}/${i}} ]] && \
-                { removal=false; break; }
-        done
+		for i in i{4,5,6}86 x86_64; do
+			[[ ${i} = ${arch} ]] && continue 2
+			[[ -d ${real_arch_dir/${arch}/${i}} ]] && \
+{ removal=false; break; }
+		done
 
-        if ! ${removal}; then
-            ewarn "Removing old build directory \
-                ${red}${real_arch_dir/\/${arch}}${nocolor}"
-            do_exec rm -rf ${real_arch_dir/\/${arch}/}
-        else
-            ewarn "Removing old build directory ${red}\
-                ${real_arch_dir}${nocolor}"
-            do_exec rm -rf ${real_arch_dir} ${real_excludes_dir}
-        fi
-    elif [[ /var/tmp/justboot != ${livedir} && \
-        -d /var/tmp/justboot/${arch} ]]; then
+		if ! ${removal}; then
+			ewarn "Removing old build directory \
+${red}${real_arch_dir/\/${arch}}${nocolor}"
+			do_exec rm -rf ${real_arch_dir/\/${arch}/}
+		else
+			ewarn "Removing old build directory ${red}\
+${real_arch_dir}${nocolor}"
+			do_exec rm -rf ${real_arch_dir} ${real_excludes_dir}
+		fi
+		elif [[ /var/tmp/justboot != ${livedir} && \
+-d /var/tmp/justboot/${arch} ]]; then
 
-        einfo "Moving build directory from ${red}/var/tmp/\
-            justboot/${arch}${nocolor} to ${red}${livedir}/${arch}\
-            .${nocolor} please wait..."
+			einfo "Moving build directory from ${red}/var/tmp/\
+justboot/${arch}${nocolor} to ${red}${livedir}/${arch}\
+.${nocolor} please wait..."
 
-        exec_chkdir ${livedir}/excludes
-        do_exec mv /var/tmp/justboot/${arch} ${arch_dir}
-        do_exec mv /var/tmp/justboot/excludes/${arch} ${excludes_dir}
+			exec_chkdir ${livedir}/excludes
+			do_exec mv /var/tmp/justboot/${arch} ${arch_dir}
+			do_exec mv /var/tmp/justboot/excludes/${arch} ${excludes_dir}
 
-        do_exec ln -sf ${arch_dir} /var/tmp/justboot/${arch}
-        do_exec ln -sf ${livedir}/excludes/${arch} \
-            /var/tmp/justboot/excludes/${arch}
-        do_exec ln -sf @datdir@ ${data_dir}
-    fi
+			do_exec ln -sf ${arch_dir} /var/tmp/justboot/${arch}
+			do_exec ln -sf ${livedir}/excludes/${arch} \
+/var/tmp/justboot/excludes/${arch}
+			do_exec ln -sf @datdir@ ${data_dir}
+		fi
 fi
 
 # Convert x86_64 arch for proper usage in Gentoo.
 case ${arch} in
-    x86_64) local gentoo_arch=amd64 stage_arch=amd64;;
-    i[4,5,6]86) local gentoo_arch=x86 stage_arch=i686
+	x86_64) local gentoo_arch=amd64 stage_arch=amd64;;
+	i[4,5,6]86) local gentoo_arch=x86 stage_arch=i686
 esac
 
 # Missing stage (possible ctrl+c) during extraction.
 [[ ! -f ${arch_dir}/build ]] && do_exec rm -rf ${arch_dir}
 
 if [ ! -d ${arch_dir} ]; then
-    einfo "Building initial stage1 for ${blue}${arch}${nocolor}. \
-        please wait..."
+	einfo "Building initial stage1 for ${blue}${arch}${nocolor}. \
+please wait..."
 
-    do_exec wget -q ${download_mirror}/releases/${gentoo_arch}/autobuilds/\
+	do_exec wget -q ${download_mirror}/releases/${gentoo_arch}/autobuilds/\
 latest-stage3.txt
 
-    local gentoo_stage=$(egrep -o \
-        [[:digit:]]{8}/stage3-${stage_arch}-[[:digit:]]{8}.tar.bz2 \
-        latest-stage3.txt)
-    do_exec rm latest-stage3.txt
+	local gentoo_stage=$(egrep -o \
+[[:digit:]]{8}/stage3-${stage_arch}-[[:digit:]]{8}.tar.bz2 \
+latest-stage3.txt)
+	do_exec rm latest-stage3.txt
 
-    exec_chkdir ${arch_dir} 
-    do_exec cd ${arch_dir} || error "Failed to switch to ${arch_dir}"
+	exec_chkdir ${arch_dir} 
+	do_exec cd ${arch_dir} || error "Failed to switch to ${arch_dir}"
 
-    einfo "Fetching gentoo ${gentoo_stage#*/} autobuild stage"
-    do_exec wget -q ${download_mirror}/releases/${gentoo_arch}\
+	einfo "Fetching gentoo ${gentoo_stage#*/} autobuild stage"
+	do_exec wget -q ${download_mirror}/releases/${gentoo_arch}\
 /autobuilds/${gentoo_stage}
 
-    einfo "Extracting ${gentoo_stage#*/}"
-    do_exec tar xjpf ${gentoo_stage#*/}
-    do_exec rm ${gentoo_stage#*/}
+	einfo "Extracting ${gentoo_stage#*/}"
+	do_exec tar xjpf ${gentoo_stage#*/}
+	do_exec rm ${gentoo_stage#*/}
 
-    einfo "Fetching portage tree snapshot"
-    do_exec wget -q ${download_mirror}/snapshots/portage-latest.tar.bz2
+	einfo "Fetching portage tree snapshot"
+	do_exec wget -q ${download_mirror}/snapshots/portage-latest.tar.bz2
 
-    einfo "Extracting portage-latest.tar.bz2"
-    do_exec tar xjpf portage-latest.tar.bz2 -C usr/
-    do_exec rm portage-latest.tar.bz2
+	einfo "Extracting portage-latest.tar.bz2"
+	do_exec tar xjpf portage-latest.tar.bz2 -C usr/
+	do_exec rm portage-latest.tar.bz2
 
-    exec_chkdir ${excludes_dir}
-    exec_chkdir /var/tmp/justboot/excludes
+	exec_chkdir ${excludes_dir}
+	exec_chkdir /var/tmp/justboot/excludes
 
-    for i in "${livecd_excludes[@]}"; do
-      exec_chkdir ${excludes_dir}/${i//\//:}
-      do_exec mv ${i}/* ${excludes_dir}/${i//\//:} &>/dev/null
-    done
+	for i in "${livecd_excludes[@]}"; do
+		exec_chkdir ${excludes_dir}/${i//\//:}
+		do_exec mv ${i}/* ${excludes_dir}/${i//\//:} &>/dev/null
+	done
 
-    einfo "Done with stage1 for ${blue}${gentoo_arch}.${nocolor}"
-    touch ${arch_dir}/build
+	einfo "Done with stage1 for ${blue}${gentoo_arch}.${nocolor}"
+	do_exec touch ${arch_dir}/build
 
-    if [[ ${livedir} != /var/tmp/justboot ]]; then
-      do_exec ln -sf ${arch_dir} /var/tmp/justboot/${arch}
-      do_exec ln -sf ${livedir}/excludes/${arch} \
-        /var/tmp/justboot/excludes/${arch}
-      do_exec ln -sf @datdir@ ${data_dir}
-    fi
+	if [[ ${livedir} != /var/tmp/justboot ]]; then
+		do_exec ln -sf ${arch_dir} /var/tmp/justboot/${arch}
+		do_exec ln -sf ${livedir}/excludes/${arch} \
+/var/tmp/justboot/excludes/${arch}
+		do_exec ln -sf @datdir@ ${data_dir}
+	fi
 fi
 
 do_exec prepare_env
@@ -658,117 +658,117 @@ do_exec mount -o bind /dev ${arch}/dev
 do_exec mount -o bind ${data_dir} ${arch}${data_dir}
 
 if [ -d /var/tmp/justboot/uclibc ]; then
-    einfo "Previous uclibc build directory found, binding to
-        ${arch_dir}/var/tmp/justboot/uclibc"
-    exec_chkdir ${arch_dir}/var/tmp/justboot/uclibc
-    do_exec mount -o bind /var/tmp/justboot/uclibc \
-        ${arch_dir}/var/tmp/justboot/uclibc
-    uclibc_bind=true
+	einfo "Previous uclibc build directory found, binding to
+${arch_dir}/var/tmp/justboot/uclibc"
+	exec_chkdir ${arch_dir}/var/tmp/justboot/uclibc
+	do_exec mount -o bind /var/tmp/justboot/uclibc \
+${arch_dir}/var/tmp/justboot/uclibc
+	uclibc_bind=true
 fi
 
 for x in "${livecd_excludes[@]}"; do
-    if (shopt -s nullglob dotglob; f=({arch}/${x//://}/!(.keep)); \
-    (( ${#f[@]} ))); then
-        einfo "Detected newly added ${blue}${x}${nocolor} for livecd \
-            excludes, moving build to ${red}${excludes_dir}/${x//\//:}\
-            .${nocolor} please wait..."
-        exec_chkdir ${excludes_dir}/${x//\//:}
-        do_exec mv ${arch}/${x}/* ${excludes_dir}/${x//\//:} &>/dev/null
-        do_exec rm -rf ${arch}/${x}/*
-    fi
+	if (shopt -s nullglob dotglob; f=({arch}/${x//://}/!(.keep)); \
+(( ${#f[@]} ))); then
+		einfo "Detected newly added ${blue}${x}${nocolor} for livecd \
+excludes, moving build to ${red}${excludes_dir}/${x//\//:}\
+.${nocolor} please wait..."
+		exec_chkdir ${excludes_dir}/${x//\//:}
+		do_exec mv ${arch}/${x}/* ${excludes_dir}/${x//\//:} &>/dev/null
+		do_exec rm -rf ${arch}/${x}/*
+	fi
 done
 
 if ${ramfs}; then
-    for x in "${livecd_excludes[@]}"; do
-        for y in "${ramfs_dir[@]}"; do
-            if [[ ${x} = ${y} ]]; then
-                einfo "Mounting ${blue}${x}${nocolor} in memory. \
-                    please wait..."
-                do_exec mount -t ramfs ${x} ${arch}/${x} 1>/dev/null
+	for x in "${livecd_excludes[@]}"; do
+		for y in "${ramfs_dir[@]}"; do
+			if [[ ${x} = ${y} ]]; then
+				einfo "Mounting ${blue}${x}${nocolor} in memory. \
+please wait..."
+				do_exec mount -t ramfs ${x} ${arch}/${x} 1>/dev/null
 
-                [[ ! -d ${excludes_dir}/${x//\//:} ]] && \
-                    exec_chkdir ${excludes_dir}/${x//\//:}
-                do_exec rsync -caq ${excludes_dir}/${x//\//:}/* \
-                    ${arch}/${x} &>/dev/null
+				[[ ! -d ${excludes_dir}/${x//\//:} ]] && \
+exec_chkdir ${excludes_dir}/${x//\//:}
+				do_exec rsync -caq ${excludes_dir}/${x//\//:}/* \
+${arch}/${x} &>/dev/null
 
-                einfo "${red}${x}${nocolor} copied to ramfs"
-                continue 2
-            fi
-        done
-        do_exec mount -o bind ${excludes_dir}/${x//\//:} \
-            ${arch}/${x} 1>/dev/null
-    done
+				einfo "${red}${x}${nocolor} copied to ramfs"
+				continue 2
+			fi
+		done
+			do_exec mount -o bind ${excludes_dir}/${x//\//:} \
+${arch}/${x} 1>/dev/null
+	done
 
-    for x in "${ramfs_dir[@]}"; do
-        for y in "${livecd_excludes[@]}"; do
-            [[ ${x} = ${y} ]] && continue 2
-        done
-        einfo "Mounting ${blue}${x}${nocolor} in memory.. please wait."
+	for x in "${ramfs_dir[@]}"; do
+		for y in "${livecd_excludes[@]}"; do
+			[[ ${x} = ${y} ]] && continue 2
+		done
+		einfo "Mounting ${blue}${x}${nocolor} in memory.. please wait."
 
-    if (shopt -s nullglob dotglob; f=(${arch}/${x}/!(.keep));\
-    (( ${#f[@]} ))); then
-        exec_chkdir ${excludes_dir}/${x//\//:}
-        einfo "${blue}${arch}/${x}${nocolor} is not empty, moving \
-            build to ${red}${excludes_dir}/${x//\//:}.${nocolor} \
-            please wait..."
-        do_exec mv ${arch}/${x}/* ${excludes_dir}/${x//\//:}\
-            &>/dev/null
-    else
+		if (shopt -s nullglob dotglob; f=(${arch}/${x}/!(.keep));\
+(( ${#f[@]} ))); then
+			exec_chkdir ${excludes_dir}/${x//\//:}
+			einfo "${blue}${arch}/${x}${nocolor} is not empty, moving \
+build to ${red}${excludes_dir}/${x//\//:}.${nocolor} \
+please wait..."
+			do_exec mv ${arch}/${x}/* ${excludes_dir}/${x//\//:}\
+&>/dev/null
+		else
 
-        for i in ${arch}/${x} ${excludes_dir}/${x//\//:}; do
-            exec_chkdir ${i}
-        done
-    fi
+			for i in ${arch}/${x} ${excludes_dir}/${x//\//:}; do
+				exec_chkdir ${i}
+			done
+		fi
 
-    do_exec mount -t ramfs ${x} ${arch}/${x} 1>/dev/null
+		do_exec mount -t ramfs ${x} ${arch}/${x} 1>/dev/null
 
-    if [[ -d ${excludes_dir}/${x//\//:} ]]; then
-        do_exec rsync -caq ${excludes_dir}/${x//\//:}/* \
-            ${arch}/${x} &>/dev/null
-        einfo "${red}${x}${nocolor} copied to ramfs"
-    fi
-    done
+		if [[ -d ${excludes_dir}/${x//\//:} ]]; then
+			do_exec rsync -caq ${excludes_dir}/${x//\//:}/* \
+${arch}/${x} &>/dev/null
+			einfo "${red}${x}${nocolor} copied to ramfs"
+		fi
+	done
 
-    (
-    cd ${excludes_dir}
-    declare -a dirs=( * )
-    for x in "${dirs[@]}"; do
-        for y in "${livecd_excludes[@]}" "${ramfs_dir[@]}"; do
-            [[ ${x} = ${y//\//:} ]] && continue 2
-        done
+	(
+	cd ${excludes_dir}
+	declare -a dirs=( * )
+	for x in "${dirs[@]}"; do
+		for y in "${livecd_excludes[@]}" "${ramfs_dir[@]}"; do
+			[[ ${x} = ${y//\//:} ]] && continue 2
+		done
 
-    einfo "${blue}${x}${nocolor} is an orphan directory."
-    einfo "Moving build to ${red}${arch}/${x//://}.${nocolor} \
-        please wait..."
-    do_exec mv ${excludes_dir}/${x}/* ${arch}/${x//://} \
-        &>/dev/null
-    do_exec rm -rf ${excludes_dir}/${x}
-    done
-    )
+		einfo "${blue}${x}${nocolor} is an orphan directory."
+		einfo "Moving build to ${red}${arch}/${x//://}.${nocolor} \
+please wait..."
+		do_exec mv ${excludes_dir}/${x}/* ${arch}/${x//://} \
+&>/dev/null
+		do_exec rm -rf ${excludes_dir}/${x}
+	done
+	)
 else
-    (
-    cd ${excludes_dir}
-    declare -a dirs=( * )
+	(
+	cd ${excludes_dir}
+	declare -a dirs=( * )
 
-    for x in "${dirs[@]}"; do
-        for y in "${livecd_excludes[@]}"; do
-        [[ ${x} = ${y//\//:} ]] && continue 2
-        done
+	for x in "${dirs[@]}"; do
+		for y in "${livecd_excludes[@]}"; do
+			[[ ${x} = ${y//\//:} ]] && continue 2
+		done
 
-        einfo "${blue}${x}${nocolor} is either an orphan directory \
-            or part of an old ${blue}ramfs (--ramfs)${nocolor} run."
-        einfo "Moving build to ${red}${arch}/${x//://}.${nocolor} \
-            please wait..."
-        do_exec mv ${excludes_dir}/${x}/* ${arch}/${x//://} &>/dev/null
-        do_exec rm -rf ${excludes_dir}/${x}
-    done
-    )
+		einfo "${blue}${x}${nocolor} is either an orphan directory \
+or part of an old ${blue}ramfs (--ramfs)${nocolor} run."
+		einfo "Moving build to ${red}${arch}/${x//://}.${nocolor} \
+please wait..."
+		do_exec mv ${excludes_dir}/${x}/* ${arch}/${x//://} &>/dev/null
+		do_exec rm -rf ${excludes_dir}/${x}
+	done
+	)
 
-    einfo "Mounting livecd build files"
-    for i in "${livecd_excludes[@]}"; do
-        do_exec mount -o bind ${excludes_dir}/${i//\//:} ${arch}/${i} \
-            1>/dev/null
-    done
+	einfo "Mounting livecd build files"
+	for i in "${livecd_excludes[@]}"; do
+		do_exec mount -o bind ${excludes_dir}/${i//\//:} ${arch}/${i} \
+1>/dev/null
+	done
 fi
 
 [[ ! -d ${arch_dir}/mnt/livecd ]] && do_exec mkdir -p ${arch_dir}/mnt/\
@@ -777,13 +777,13 @@ livecd/{static,image,dynamic}
 einfo "Entering the livecd chroot environment"
 
 do_exec chmod +x ${chroot_script} && do_exec mv ${chroot_script} \
-    ${arch_dir}/tmp
+${arch_dir}/tmp
 do_exec cp /etc/resolv.conf ${arch_dir}/etc
 
 if [[ ${arch} =~ ^i[4-6]86$ ]]; then
-    do_exec linux32 chroot ${arch_dir} ${chroot_script} 
+	do_exec linux32 chroot ${arch_dir} ${chroot_script} 
 else
-    do_exec linux64 chroot ${arch_dir} ${chroot_script}
+	do_exec linux64 chroot ${arch_dir} ${chroot_script}
 fi
 
 if [[ $? =~ ^(1|13)$ ]]; then
@@ -838,14 +838,14 @@ ISOLINUX
 # options.
 clean_env() {
 
-local target=${livedir}/targets/${arch} 
+local target=${livedir}/targets/${arch}
 local cleanup_script=$(mktemp /tmp/XXX)
 
 [ -d ${target} ] && do_exec rm -rf ${target}/*
 [ -d ${livedir}/boot ] && do_exec rm -rf ${livedir}/targets/boot
 
 for i in "${target}" "${livedir}/targets/boot/isolinux"; do
-    exec_chkdir ${i}
+	exec_chkdir ${i}
 done
 
 einfo "Performing livecd cleanup. please wait as this can take a while..."
