Minor Changes

diff --git a/justboot b/justboot
--- a/justboot
+++ b/justboot
@@ -207,9 +207,9 @@ while [ $# -gt 0 ]; do
     --coprocessor=*) 
       CPU="${1##*=}"
       if [[ -z ${PROCS[${CPU}]} ]]; then
-        ewarm "${CPU} is an invalid --coprocessor option."
+        ewarn "${CPU} is an invalid --coprocessor option."
         einfo "Available options are: i386,i486,i586,i686,mk6,mk7,mk8,opteron,core2 & generic"
-        ewarm "Exiting now."; exit 1
+        ewarn "Exiting now."; exit 1
       fi
       ;;
     --verbose) VERBOSE=0;;
