Minor issues with globals opts and whitespace, next commits will fix the rest of that.

diff --git a/justboot.in b/justboot.in
--- a/justboot.in
+++ b/justboot.in
@@ -52,22 +52,22 @@ if ! declare -A &>/dev/null; then
 else
 	bash4=true
 	declare -A procs=( [i386]=M386 [i486]=M486 [i586]=M586
-        [i686]=M686 [pentiumII]=MPENTIUMII [pentiumIII]=MPENTIUMIII
+		[i686]=M686 [pentiumII]=MPENTIUMII [pentiumIII]=MPENTIUMIII
 		[pentium-mmx]=MPENTIUMM [pentium4]=MPENTIUM4 [k6]=MK6
 		[k7]=MK7 [k8]=MK8 [opteron]=MK8 [core2]=MCORE2 [core2dou]=MCORE2
 		[generic]=GENERIC_CPU [x86_64]=GENERIC_CPU [atom]=MATOM [k10]=MK10 )
 fi
 
 declare -a livecd_excludes=( $(grep -v '^#' \
-    @confdir@/files/excluded-directories.lst ) )
+	@confdir@/files/excluded-directories.lst ) )
 declare -a remove_packages=( $(grep -v '^#'  \
-    @confdir@/files/remove-packages.lst ) )
+	@confdir@/files/remove-packages.lst ) )
 declare -a remove_files=( $(grep -v '^#'  \
-    @confdir@/files/remove-files.lst ) )
+	@confdir@/files/remove-files.lst ) )
 declare -a ramfs_dir=( $(grep -v '^#' \
-    @confdir@/files/ramfs-directories.lst ) )
+	@confdir@/files/ramfs-directories.lst ) )
 declare -a extra_packages=( $(grep -v '^#' \
-    @confdir@/files/extra-packages.lst ) )
+	@confdir@/files/extra-packages.lst ) )
 declare -a arches=( x86_64 i486 i586 i686 )
 declare -a locales=( $(<@confdir@/locale.gen) )
 
@@ -91,91 +91,89 @@ exec_chkdir() {
 	[[ ! -d ${dir} ]] && mkdir -p ${dir}
 }
 do_exec() {
-  if ${debug}; then
-    echo -e "\a${red}debug:${nocolor}${blue} (${@})"${nocolor}
-    "${@}"
-  elif ${verbose}; then
-    "${@}"
-  else
-    "${@}" 2>/dev/null
-  fi
+if ${debug}; then
+	echo -e "\a${red}debug:${nocolor}${blue} (${@})"${nocolor}
+	"${@}"
+elif ${verbose}; then
+	"${@}"
+else
+	"${@}" 2>/dev/null
+fi
 }
 
 # Help menu
 print_help() {
-cat << HELP
+cat <<-HELP
 Usage: justboot [arguments] [make opts] [kernel opts]
 
 Arguments:
 
---arch=                 - Set arch for livecd build i.e --arch=x86_64
---kernel=               - Kernel sources for livecd
---root-passwd=          - ROOT password for the livecd
---init-compression      - Currently only gzip and lzma compression is
-	supported
--L, --volid=            - Set a label for the livecd image
---ramfs                 - Compile in ramfs "Must have ~4GB of available
-	RAM"
---force-toolchain       - Force a rebuilt of the toolchain
---skip-toolchain        - Skips toolchain built for those in a hurry
---build-directory=       - Set the build directory for compiles
---package-manager=      - Enable the package manager for all builds
-	.: Currently only pkgcore is supported, by default justboot uses
-	portage :.
---letmein               - Will run interactive bash at end of chroot
-	stage so you can tweak the livecd environment
---verbose               - Run in verbose mode - lots of output
---purge                 - Purge old build and start fresh
---delete-arch           - Like --purge but exits script after
---debug                 - Turn on debugging
+--arch=					- Set arch for livecd build i.e --arch=x86_64
+--kernel=				- Kernel sources for livecd
+--root-passwd=			- ROOT password for the livecd
+--init-compression		- Currently only gzip and lzma compression is
+						supported
+-L, --volid=			- Set a label for the livecd image
+--ramfs					- Compile in ramfs "Must have ~4GB of available
+						RAM"
+--force-toolchain		- Force a rebuilt of the toolchain
+--skip-toolchain		- Skips toolchain built for those in a hurry
+--build-directory=		- Set the build directory for compiles
+--package-manager=		- Enable the package manager for all builds
+.: Currently only pkgcore is supported, by default justboot uses portage :.
+--letmein				- Will run interactive bash at end of chroot
+						stage so you can tweak the livecd environment
+--verbose				- Run in verbose mode - lots of output
+--purge					- Purge old build and start fresh
+--delete-arch			- Like --purge but exits script after
+--debug					- Turn on debugging
 
 Gentoo make.conf options:
 
---cflags                - Compiler FLAGS
---ldflags=              - Linker FLAGS
---make-opts=            - MAKEOPTS
---keywords=             - Accepted KEYWORDS i.e ~x86
---jobs=                 - Specifies the number of packages to build
-	simultaneously
---use=                  - Packages USE flags
---features=             - make.conf specific FEATURES
---gentoo-mirrors=       - JustBOOT and make.conf space separated list
-	of local mirrors
---rsync-mirror=         - Sets the default rsync mirror
---niceness=             - make.conf specific PORTAGE_NICENESS
+--cflags				- Compiler FLAGS
+--ldflags=				- Linker FLAGS
+--make-opts=			- MAKEOPTS
+--keywords=				- Accepted KEYWORDS i.e ~x86
+--jobs=					- Specifies the number of packages to build
+						simultaneously
+--use=					- Packages USE flags
+--features=				- make.conf specific FEATURES
+--gentoo-mirrors=		- JustBOOT and make.conf space separated list
+						of local mirrors
+--rsync-mirror=			- Sets the default rsync mirror
+--niceness=				- make.conf specific PORTAGE_NICENESS
 
 Linux Kernel options: >=bash-4.0 Only
 
---coprocessor=          - Processor type for the livecd kernel i.e
-	--coprocessor=core2
---coprocessor-list      - List the currently supported coprocessors
---menuconfig            - Runs make menuconfig for interactive kernel
-	configuration
---purge-kernel          - Purge any kernel sources and start fresh
+--coprocessor=			- Processor type for the livecd kernel
+--coprocessor-list		- List the currently supported coprocessors
+--menuconfig			- Runs make menuconfig for interactive kernel
+						configuration
+--purge-kernel			- Purge any kernel sources and start fresh
 
 Usage examples:
 
 Generate a x86_64 livecd using gentoo-sources and set 'justboot'
-    for root password
+for root password
 # justboot --arch=x86_64 --root-passwd="justboot"
 
 Generate a i686 livecd with 'let me in!' as password and 'justboot' for
-    livecd label
+livecd label
 # justboot --arch=i686 --volid="gentoo rocks" --root-passwd="let me in!"
 
 Generate a x86_64 livecd with optional gzip compression
-    (Default is to use lzma)
+(Default is to use lzma)
 # justboot --arch=x86_64 --init-compression lzma
 
 Generate a livecd but compile packages in ram (see
-    @confdir@/files/ramfs-directories.lst)
+@confdir@/files/ramfs-directories.lst)
 # justboot --arch=x86_64 -ramfs -L "Fast is good"
 
 Generate a livecd but delete old sources first.
 # justboot --arch=x86_64 --purge
 
 Generate a livecd for x86_64 using -j8 for makeopts and -19 for portage
-    niceness
+niceness
 # justboot --arch=x86_64 --make-opts="-j8" --niceness="-19"
 
 Change the livecd build directory
@@ -183,20 +181,19 @@ Change the livecd build directory
 
 Change the rsync and gentoo mirrors setting
 # justboot --arch=i486 --gentoo-mirrors="http://mirror.datapipe.net/gentoo
-	ftp://gentoo.chem.wisc.edu/gentoo/"
-    --rsync-mirror="http://localhost/portage"
+ftp://gentoo.chem.wisc.edu/gentoo/" --rsync-mirror="http://localhost/portage"
 
 Generate a livecd for opteron processors
 # justboot --coprocessor=opteron --arch=x86_64 --cflags="-march=opteron
-    -Os -pipe" --make-opts=-j3
+-Os -pipe" --make-opts=-j3
 
 Generate a livecd for an Intel Core2 Quad processor
 # justboot --coprocessor=core2 --arch=x86_64 --cflags="-march=core2 -Os -pipe"
-    --make-opts=-j5
+--make-opts=-j5
 
 Generate a x86_64 livecd with interactive kernel menu and custom rsync mirror
 # justboot --arch=x86_64 --menuconfig --make-opts=-j5
-	--rsync-mirror="http://localhost/portage"
+--rsync-mirror="http://localhost/portage"
 
 Use sys-apps/pkgcore for all livecd builds instead of portage
 # justboot --arch=i486 --package-manager=pkgcore --root-passwd=letmein
@@ -212,13 +209,14 @@ einfo "${blue}JustBOOT(tm)${nocolor} initiated"
 
 # Parse Command Line Arguments
 while [ $# -gt 0 ]; do
-    case "$1" in
-        --arch=*)
-            arch="${1#*=}"
-            einfo "${blue}${arch}${nocolor} arch set"
-            ;;
-        --cflags=*)
-            CFLAGS="${1#*=}"
+
+	case "$1" in
+		--arch=*)
+			arch="${1#*=}"
+			einfo "${blue}${arch}${nocolor} arch set"
+			;;
+		--cflags=*)
+			CFLAGS="${1#*=}"
             einfo "CFLAGS set to ${blue}\"${CFLAGS}\""
             ;;
         --ldflags=*) LDFLAGS="${1#*=}";;
@@ -506,7 +504,7 @@ check_deps() {
 local -a deps=( 'mksquashfs:sys-fs/squashfs-tools'
     'mkisofs:virtual/cdrtools' 'isohybrid:sys-boot/syslinux' )
 
-if [[ "${pms}" = pmerge ]]; then
+if [[ "${pms/ -q/}" = pmerge ]]; then
     if ! hash pmerge &>/dev/null; then
         einfo "Compiling ${blue}sys-apps/pkgcore${nocolor}"
         do_exec emerge pkgcore 1>/dev/null
@@ -975,7 +973,7 @@ uclibc_src_uri="http://gentoo.mirrors.tds.net/gentoo/experimental/\
 x86/embedded/stages/stage3-x86-uclibc-2008.0.tar.bz2"
 busybox_src_uri="http://busybox.net/downloads/busybox-1.17.2.tar.bz2"
 busybox_archive=\$(echo \${busybox_src_uri} | egrep -o \
-    'busybox-[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+\.tar\.bz2')
+'busybox-[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+\.tar\.bz2')
 busybox_conf=${data_dir}/busybox/.config
 busybox=\${busybox_archive/.tar.bz2/}
 blue="\$(tput setaf 4)"
@@ -1010,7 +1008,7 @@ fi
 
 check_deps() {
 # Check for pkgcore if --package-manager=pkgcore is used
-if [[ "${pms}" = pmerge ]]; then
+if [[ "${pms/ -q/}" = pmerge ]]; then
     if ! hash pmerge &>/dev/null; then
         einfo "Compiling \${blue}sys-apps/pkgcore\${nocolor}"
         do_exec emerge pkgcore 1>/dev/null
@@ -1079,7 +1077,7 @@ for i in \${global_packages[@]}; do
     fi
 done
 
-for i in ${extra_packages=[@]}; do
+for i in ${extra_packages[@]}; do
     if ! hash \${i/:*/} &>/dev/null; then
         einfo "Compiling \${blue}\${i}\${nocolor}"
         do_exec ${pms} \${i/*:/} 1>/dev/null
@@ -1159,9 +1157,9 @@ do_exec mknod dev/tty1 c 4 1
 do_exec cp -a /lib/modules/\${kernel_module_src} lib/modules/
 
 [ -f /boot/${arch}-initramfs_data.cpio.${init_compression} ] \
-    && do_exec rm /boot/${arch}-initramfs_data.cpio.${init_compression}
+&& do_exec rm /boot/${arch}-initramfs_data.cpio.${init_compression}
 find | cpio --quiet -o -H newc | ${init_compression} -9 \
-    >/boot/${arch}-initramfs_data.cpio.${init_compression}
+>/boot/${arch}-initramfs_data.cpio.${init_compression}
 }
 
 # This function handles the custom kernel options with --coprocessor
@@ -1169,13 +1167,13 @@ find | cpio --quiet -o -H newc | ${init_compression} -9 \
 do_coprocessor() {
 # Detect non x86_64 processors with --co-processor=x86_64
 [[ \${1} = x86_64 && ${procs[${cpu}]} =~ ^(M[4-6]86|MPENTIUMM|MK[6-7])$ \
-    ]] && { ewarn "${procs[${cpu}]} invalid for x86_64 arch"; return 1; }
+]] && { ewarn "${procs[${cpu}]} invalid for x86_64 arch"; return 1; }
 
 if [[ ${procs[${cpu}]} =~ ^M([5-6]86|PENTIUM(4|M|II|III)|CORE2|ATOM|K[6-8])$ \
 ]]; then
 	if [[ ${procs[${cpu}]} = MK10 && ${kernel_sources} != zen-sources ]]; then
 		ewarn "${procs[${cpu}]} requires zen-sources kernel to work. Falling \
-			back to K8!"
+back to K8!"
 		cpu=K8
 	fi
     patch -sp0 <${kernel_sources}-${procs[${cpu}]}.patch
@@ -1184,7 +1182,7 @@ fi
 
 prepare_kernel_opts() {
 cd ${data_dir}/kernel/\${1} || error "Could not switch to kernel \
-	source directory"
+source directory"
 
 # --coprocessor options are only patched in if we used anything besides
 # i486 or x86_64.
@@ -1201,13 +1199,13 @@ fi
 
 do_kernel_compile() {
 if ! grep "sys-kernel/${kernel_sources} symlink" \
-    /etc/portage/package.use 1>/dev/null; then
+/etc/portage/package.use 1>/dev/null; then
     echo "sys-kernel/${kernel_sources} symlink">>/etc/portage/\
 package.use
 fi
 
-do_exec emerge ${kernel_sources} 1>/dev/null || error "Failed to emerge\
-	${kernel_sources}!!!"
+do_exec emerge ${kernel_sources} 1>/dev/null || error "Failed to emerge \
+${kernel_sources}!!!"
 }
 
 # JustBOOT kernel compilation and customization options
@@ -1215,9 +1213,9 @@ prepare_kernel() {
 local date=$(date +%Y%m%d-%H%m)
 
 if ${purge_kernel}; then
-    ewarn "--purge-kernel used, removing sources..."
-    do_exec unlink /usr/src/linux
-    do_exec rm -rf /usr/src/* /lib/modules/*
+	ewarn "--purge-kernel used, removing sources..."
+	do_exec unlink /usr/src/linux
+	do_exec rm -rf /usr/src/* /lib/modules/*
 elif [ -h /usr/src/linux ]; then
 	# Create a fresh link to kernel source
 	local kernel_name=${kernel_sources%-*}
@@ -1233,60 +1231,60 @@ case ${arch} in i[4,5,6]86) local arch=x86;; esac
 
 if [[ ! -h /usr/src/linux || ! \$(ls -d /var/db/pkg/sys-kernel/\
 ${kernel_sources}-[0-9]* 2>/dev/null) ]]; then
-    einfo "Compiling \${blue}${kernel_sources}\${nocolor}."
-    do_kernel_compile
+	einfo "Compiling \${blue}${kernel_sources}\${nocolor}."
+	do_kernel_compile
 
-    einfo "Compiling \${blue}\${arch}\${nocolor} kernel image"
-    if declare -A &>/dev/null; then
-        if ${coprocessor}; then
-            do_exec prepare_kernel_opts \${arch}
-			do_exec mv ${data_dir}/kernel/\${arch}/.config \
-/usr/src/linux/.config
-        else
-            do_exec cp ${data_dir}/kernel/\${arch}/${kernel_sources} \
-/usr/src/linux/.config
-        fi
-    fi
-	
-	do_exec cd /usr/src/linux || error "Failed to switch to \
-		kernel source directory"
-
-    if ${menuconfig}; then
-      do_exec make menuconfig
-      do_exec make ${MAKEOPTS} 1>/dev/null
-    else
-      do_exec make ${MAKEOPTS} 1>/dev/null
-    fi
-
-    do_exec make modules_install 1>/dev/null
-    einfo "\${red}\${arch}\${nocolor} kernel compiled, preparing \
-        initramfs image."
-    do_exec prepare_initramfs
-else
-    if [ -f /usr/src/linux/.config ]; then
-      einfo "Backing up old kernel config to \${red}/usr/src/linux/\
-.config.\${date}\${nocolor}"
-      do_exec cp /usr/src/linux/.config /usr/src/linux/.config.\
-${kernel_sources}-\${date}
-    fi
-
-    einfo "Compiling \${red}\${arch}\${nocolor} kernel image"
-
-    if declare -A &>/dev/null; then
-        if ${coprocessor}; then
-            do_exec prepare_kernel_opts \${arch}
+	einfo "Compiling \${blue}\${arch}\${nocolor} kernel image"
+	if declare -A &>/dev/null; then
+		if ${coprocessor}; then
+			do_exec prepare_kernel_opts \${arch}
 			do_exec mv ${data_dir}/kernel/\${arch}/.config \
 /usr/src/linux/.config
 		else
-            do_exec cp ${data_dir}/kernel/\${arch}/${kernel_sources} \
+			do_exec cp ${data_dir}/kernel/\${arch}/${kernel_sources} \
 /usr/src/linux/.config
-        fi
-    fi
+		fi
+	fi
 
 	do_exec cd /usr/src/linux || error "Failed to switch to \
-		kernel source directory"
+kernel source directory"
 
-    if ${menuconfig}; then
+	if ${menuconfig}; then
+		do_exec make menuconfig
+		do_exec make ${MAKEOPTS} 1>/dev/null
+	else
+		do_exec make ${MAKEOPTS} 1>/dev/null
+	fi
+
+	do_exec make modules_install 1>/dev/null
+	einfo "\${red}\${arch}\${nocolor} kernel compiled, preparing \
+initramfs image."
+	do_exec prepare_initramfs
+else
+	if [ -f /usr/src/linux/.config ]; then
+		einfo "Backing up old kernel config to \${red}/usr/src/linux/\
+.config.\${date}\${nocolor}"
+		do_exec cp /usr/src/linux/.config /usr/src/linux/.config.\
+${kernel_sources}-\${date}
+fi
+
+	einfo "Compiling \${red}\${arch}\${nocolor} kernel image"
+
+	if declare -A &>/dev/null; then
+		if ${coprocessor}; then
+			do_exec prepare_kernel_opts \${arch}
+			do_exec mv ${data_dir}/kernel/\${arch}/.config \
+/usr/src/linux/.config
+		else
+			do_exec cp ${data_dir}/kernel/\${arch}/${kernel_sources} \
+/usr/src/linux/.config
+		fi
+fi
+
+	do_exec cd /usr/src/linux || error "Failed to switch to \
+kernel source directory"
+
+	if ${menuconfig}; then
       do_exec make menuconfig
       do_exec make ${MAKEOPTS} 1>/dev/null
     else
